<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
    <p class="product-image product-image-zoom" id="product-image">
        <?php
        $_img = '<img id="image" src="' . $this->helper('catalog/image')->init($_product, 'image') . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
    <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
    <div class="zoom">
        <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
        <div id="track">
            <div id="handle"></div>
        </div>
        <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
    </div>
    <script type="text/javascript">
    //<![CDATA[
        Event.observe(window, 'load', function() {
            product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
        });
    //]]>
    </script>
<?php else: ?>
    <p class="product-image">
        <?php
        $_img = '<img src="' . $this->helper('catalog/image')->init($_product, 'image')->resize(265) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0): ?>
    <div class="more-views" id="media">
        <h2><?php echo $this->__('More Views') ?></h2>
        <ul>
                <li>
                    <a href="#" onclick="swapBaseImage('<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_product->getImage())->resize(265); ?>');return false;" title="">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_product->getImage())->resize(56); ?>" />
                    </a>
                </li>
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php if(!strpos($_image->getUrl(), $_product->getImage())): ?>
                <li>
                    <a href="#" onclick="swapBaseImage('<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(265); ?>');return false;" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                    </a>
                </li>
                <?php  endif; ?>
            <?php endforeach; ?>
            <?php if (count($this->getVideoCollection()->getData()) > 0): ?>
                <?php foreach ($this->getVideoCollection()->getData() as $_video): ?>
                    <li>
                        <a href='javascript:void(0);' style="background: url('<?php echo $this->getVideoImage($_video['video_url']); ?>');" class="videoLink">
                            <img src="<?php echo $this->getSkinUrl("images/videogallery/media-mask.png"); ?>" id="video_<?php echo $_video['video_id']; ?>"/>
                        </a>
                        <input type="hidden" value="<?php echo $this->getVideoEmbedUrl($_video['video_url']); ?>" />
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </div>
<?php else: ?>
    <div class="more-views" id="media">
        <h2><?php echo $this->__('More Views') ?></h2>
        <ul>
            <li>
                <a href="#" onclick="swapBaseImage('<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_product->getImage())->resize(265); ?>');return false;" title="">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_product->getImage())->resize(56); ?>" />
                </a>
            </li>
            <?php if (count($this->getVideoCollection()->getData()) > 0): ?>
                <?php foreach ($this->getVideoCollection()->getData() as $_video): ?>
                    <li>
                        <a href='javascript:void(0);' style="background: url('<?php echo $this->getVideoImage($_video['video_url']); ?>');" class="videoLink">
                            <img src="<?php echo $this->getSkinUrl("images/videogallery/media-mask.png"); ?>" id="video_<?php echo $_video['video_id']; ?>"/>
                        </a>
                        <input type="hidden" value="<?php echo $this->getVideoEmbedUrl($_video['video_url']); ?>" />
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </div>                    
<?php endif; ?>
<?php if (count($this->getVideoCollection()->getData()) > 0): ?>
    <script type="text/javascript">
        $('media').observe('click', function(event) {
            if (event.target.tagName === 'IMG') {
                if(event.target.id){
                    var image = event.target;
                    showIframe(image);
                }else{
                    hideIframe();
                }
            }
        });
        
        function showIframe(image){
            $('product-image').down("img").hide();
            $('track_hint').hide();
            $$('div.zoom')[0].hide();
            if($('product-image').down("iframe"))
                $('product-image').down("iframe").remove();
            var iframe = '<iframe width="100%" height="100%" src="' + image.up('li').down('input').value + '" frameborder="0" allowfullscreen></iframe>';
            $('product-image').insert(iframe);
        }
        function hideIframe(){
            if($('product-image').down("iframe")){
                $('product-image').down("iframe").remove();
                $('product-image').down("img").show();
                $('track_hint').show();
                $$('div.zoom')[0].show();
            }
        }
        function swapBaseImage(imageUrl){
            $('product-image').down("img").src=imageUrl;
        }
    </script>
<?php endif; ?>